# Generated by Django 5.2.8 on 2025-11-08 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email address to contact the owner', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Name of the pet owner', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PetContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Contact Request',
                'verbose_name_plural': 'Pet Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
